### ISSUE TITLE
Logs plugin enhancements

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio-next#1006]
The logs plugin currently sorts from oldest to newest log. I would expect the exact opposite behavior. For monitoring I would want to know what's happening in the application right now. There could optionally be a toggle to sort as the users want it.

**Comment by mmelko** [comment]
Hi Martin, I can look at this.

**Comment by mmuzikar** [comment]
Closing as already done in https://github.com/hawtio/hawtio-next/pull/1063
