### ISSUE TITLE
About - Background image isn't displayed

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#1031]
Running `yarn start` and open the about modal:

![image](https://github.com/user-attachments/assets/87977805-0423-4c38-9633-8d314d4a3ff4)

while the PF 5 demo looks like:

https://www.patternfly.org/components/about-modal/

![image](https://github.com/user-attachments/assets/03d6cc3a-2bc0-40cf-80ea-76f7d44e5766)

**Comment by tadayosi** [comment]
@mmelko Can you have a look?

**Comment by mmelko** [comment]
yeah I will look at this. IIRC it's not actual background but rather svg icon scaled big.
