### ISSUE TITLE
Add jest as a unit testing suite for testing react components and code

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-next#11]

**Comment by phantomjinx** [comment]
Jest is currently missing and not configured so going to complete scaffolding to begin executing unit tests.

**Comment by tadayosi** [comment]
@phantomjinx Thanks for the reporting.

Doesn't `yarn test` work for you?  Create React App uses [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/) and Jest should be available as its dependency. For example, we already have something like these:
https://github.com/hawtio/hawtio-next/blob/main/src/hawtio/Hawtio.test.tsx
https://github.com/hawtio/hawtio-next/blob/main/src/hawtio/util/strings.test.ts

**Comment by phantomjinx** [comment]
It originally complained that `jest` was not installed, despite a `yarn install`. I have added it for the moment and got most of the test suites passing (issues with `global.fetch` mocking mostly). I'll remove it and see if a `yarn install` does bring it back in.
