### ISSUE TITLE
Make sure monaco-editor is not loaded from CDN

### ISSUE THREAD

**Issue by grgrzybek** [hawtio/hawtio-next#1186]
See hawtio/hawtio-online#552

**Comment by grgrzybek** [comment]
The thing is that we had to add CDN host used by monaco-editor to CSP headers.

We use `@patternfly/react-code-editor` which is a wrapper over `@monaco-editor/react` which loads some code from https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/

But:
* we don't want to pollute `script-src-elem` element of `Content-Security-Policy` header
* we want to package the code for offline/no-Internet-access usage

There's a default config:
```javascript
var config = {
  paths: {
    vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs'
  }
};
```

in `node_modules/@monaco-editor/loader/lib/es/config/index.js`, but [this page](https://www.npmjs.com/package/@patternfly/react-code-editor#to-use-monaco-editor-as-an-npm-package-and-avoid-using-cdn) shows how to change this.
We need to add `monaco-editor` explicit dependency to `package.json` and use this code, where `<CodeEditor>` element is used:
```javascript
import * as monaco from 'monaco-editor';
import { loader } from '@monaco-editor/react';

loader.config({ monaco });
```

cc: @tadayosi @phantomjinx @mmelko

**Comment by hvaoc** [comment]
This does not work with Next 15.3

<img width="1053" alt="Image" src="https://github.com/user-attachments/assets/013c4bc6-ec31-446b-a056-dcac64f24de0" />

I also want to make it work with static export. Want to package monaco with No internet scenario

**Comment by grgrzybek** [comment]
Are you trying to use Hawtio with Next.js? We've never supported it...
