### ISSUE TITLE
JMX - Refactor the Attributes Component to include tabular form of multiple beans

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-next#125]
The old Attributes Component includes the ability to display the children of a group category, eg. Contexts, as a table with the bean attributes as the columns and mbeans as the rows:

![jmx-contexts-screenshot-old](https://user-images.githubusercontent.com/1634180/222115965-baa5cf5b-6dbd-45f8-a56f-ac0e1f2bceed.png)

Old Attributes component for camel contexts ^

**Comment by tadayosi** [comment]
@joshiraez You can work on this too.

**Comment by joshiraez** [comment]
I'm picking this up then and using @phantomjinx approach in camel as a base. I'll do it after the current camel help page

**Comment by joshiraez** [comment]
I spoke with Paul and I'll be picking this up to continue the work on the JMX plugin. From the mentioned Camel issue for the attributes view it seems they should be similar so I'll tr to take that as a base

**Comment by joshiraez** [comment]
@tadayosi Just to be sure, this extends #10 right? The chart component should be used for this
