### ISSUE TITLE
Determine and Refactor Camel 'Contexts' to assume single context per domain

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-next#126]
The existing app presumes a JMX/Camel application containing multiple Contexts. As such the `Contexts` page works on the premise of multiple contexts, ie. arrays, collections ...  If the assumption is that there is only one context per application then the premise of multiple contexts no longer applies and the `Contexts` page can be modified to only display the known single context.

**Comment by tadayosi** [comment]
So far we've decided to live with multiple Camel Contexts. From the Camel plugin point of view, it's just that the plugin looks for mbeans with names `org.apache.camel:type=context,*`, so it's still natural to expect there might be multiple context provided.

Let's close this issue for now. We can revisit the topic later with a new issue.
