### ISSUE TITLE
Camel - Routes - Type Converters tab

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#145]
Enable and view statistics for type converters in the routes

**Comment by phantomjinx** [comment]
Cannot provide data for the TypeConverter table due to #151

**Comment by tadayosi** [comment]
OK, then we can push this feature from 0.2.0 to future releases. We can work on it once we come up with an alternative way to implement it, or decide not to do it if it doesn't make sense to provide the feature for Camel 3 at all.

**Comment by tadayosi** [comment]
According Claus, it doesn't make sense to provide this feature for Camel 3 https://github.com/hawtio/hawtio-next/issues/151#issuecomment-1471428156. Let's just remove the feature from Hawtio NG.
