### ISSUE TITLE
TypeConverter View cannot populate type converters table

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-next#151]
The TypeConverter view is not able to populate the table of TypeConverter from/to types since the JMX operation "listTypeConverters" was removed in the Camel upgrade from [Camel 3.6 -> 3.7](https://camel.apache.org/manual/camel-3x-upgrade-guide-3_7.html#_type_converters).

This also affects current releases of hawtio. The table will only display "No data available in table" and the console will show the error:
```
Possibly unhandled rejection: java.lang.IllegalArgumentException : No operation listTypeConverters found on MBean org.apache.camel:context=SampleCamel,name=DefaultTypeConverter,type=services
```

-----
related to #145

**Comment by tadayosi** [comment]
@davsclaus Is there an alternative way to list Type Converters defined in a Camel context for the recent versions of Camel 3?  Considering the optimisation done for type converters on Camel 3, doesn't it even make sense for a console like Hawtio to provide the Type Converters view at all?

**Comment by davsclaus** [comment]
No just remove that view

**Comment by tadayosi** [comment]
Thanks Claus, then let's remove this feature from Hawtio NG.
