### ISSUE TITLE
Logs plugin

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#153]
Port [Logs](https://github.com/hawtio/hawtio-integration/tree/main/plugins/logs) plugin from legacy Hawtio, which enables you to view server-side logs on the console.

It should show logs from server side in a table with filtering on log level, logger, message, and MDC properties.

Under the hood, it uses [LogQueryMBean](https://github.com/hawtio/hawtio/blob/3.x/plugins/hawtio-log/src/main/java/io/hawt/log/support/LogQuerySupport.java) to fetch the logs from server side. Currently it only supports [Logback](https://github.com/hawtio/hawtio/tree/3.x/plugins/hawtio-log-logback).

![Logs](https://user-images.githubusercontent.com/156692/225541358-18a6fd2b-e256-4643-9427-1682cb1d9bcf.png)

**Comment by tadayosi** [comment]
cc @joshiraez @lhein

**Comment by joshiraez** [comment]
Thank you Tada, I'll be working on this

**Comment by tadayosi** [comment]
I'll take this one due to the work assignment replanning.
