### ISSUE TITLE
Remove tilde from the name of MBeans node in Camel tree

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#154]
Right now, in the Camel tree the MBean node has tilde before its name, `~MBean`. I guess it's because of convenience of sorting for putting it to the bottom in order, but ideally we should remove tilde by improving the sort argorithm in the Camel plugin.

![Camel tree](https://user-images.githubusercontent.com/156692/225554821-c3dfe98c-f298-4eac-b9b4-604ec1b69d08.png)

**Comment by tadayosi** [comment]
@phantomjinx Is my understanding correct? Is it easy to fix this?

**Comment by phantomjinx** [comment]
> @phantomjinx Is my understanding correct? Is it easy to fix this?

Yes. That's right. It was a stop-gap so I'll look at removing it next.
