### ISSUE TITLE
Spring Boot plugin

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#165]
Port [Spring Boot](https://github.com/hawtio/hawtio-integration/tree/main/plugins/spring-boot) plugin from legacy Hawtio, which provides you with the following views for a Spring Boot application.

- [x] https://github.com/hawtio/hawtio-next/issues/166
- [x] https://github.com/hawtio/hawtio-next/issues/167
- [x] https://github.com/hawtio/hawtio-next/issues/168
- [x] https://github.com/hawtio/hawtio-next/issues/169

**Comment by mmelko** [comment]
fixed by: https://github.com/hawtio/hawtio-next/pull/680, https://github.com/hawtio/hawtio-next/pull/669
