### ISSUE TITLE
Spring Boot - Health

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#166]
Show info from Spring Boot Health endpoint.
https://github.com/hawtio/hawtio-integration/tree/main/plugins/spring-boot/health

![image](https://user-images.githubusercontent.com/156692/226290539-9c2e4ed4-efb8-4b54-b16b-74e094978d09.png)

**Comment by mmelko** [comment]
fixed by: https://github.com/hawtio/hawtio-next/pull/669
