### ISSUE TITLE
Spring Boot - Info

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#167]
Show info from Spring Boot application.properties (and others).
https://github.com/hawtio/hawtio-integration/tree/main/plugins/spring-boot/info

![image](https://user-images.githubusercontent.com/156692/226291041-de08e2b0-9015-42d7-8260-73b65e7a2dd9.png)

**Comment by mmelko** [comment]
fixed by: https://github.com/hawtio/hawtio-next/pull/669
