### ISSUE TITLE
Spring Boot - Loggers

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#168]
View and configure loggers settings for a Spring Boot application.
https://github.com/hawtio/hawtio-integration/tree/main/plugins/spring-boot/loggers

![image](https://user-images.githubusercontent.com/156692/226291557-8724b052-77fc-4592-a1e7-40b3ee17b721.png)

**Comment by mmelko** [comment]
fixed by: https://github.com/hawtio/hawtio-next/pull/669
