### ISSUE TITLE
Spring Boot - Trace

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#169]
Show trace info from a Spring Boot application.
https://github.com/hawtio/hawtio-integration/tree/main/plugins/spring-boot/trace

![image](https://user-images.githubusercontent.com/156692/226292085-e48c5adb-13aa-404a-82eb-007f4015484a.png)

**Comment by mmelko** [comment]
fixed by: https://github.com/hawtio/hawtio-next/pull/680
