### ISSUE TITLE
Camel - Specialised tree view for Camel contexts

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#17]
JMX plugin provides the general JMX MBean tree from workspace. A plugin that works on top of the MBean tree like Camel plugin needs to implement a way to postprocess and decorate them into a specialised view of the tree.

- Extract only Camel-related MBeans from the entire JMX tree
- Assign custom icons according to the types of Camel MBeans

The Camel tree view from the original Hawtio looks like this:

![Camel context tree](https://user-images.githubusercontent.com/156692/213122962-285cd7a4-717d-44aa-8d1e-f1b5af0bdc2e.png)

**Comment by tadayosi** [comment]
@phantomjinx Has this been completed yet?  If completed, please close it.

Also, I'd prefer to refer to this ticket from commit message or the text of the pull req. This is so that other members can easily track the correspondence between the ticket and the fix. Thanks.

**Comment by phantomjinx** [comment]
Yes. This was taken care of as part of the camel plugin work. The specific PR is https://github.com/hawtio/hawtio-next/pull/93.
