### ISSUE TITLE
Upgrade instance of Patternfly Table to TableComposable

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-next#180]
[Table](https://www.patternfly.org/v4/components/table/react-legacy) component is being replaced with [TableComposable](https://www.patternfly.org/v4/components/table). While some table instances have been upgraded, some, eg. InFlightExchanges, still use the legacy version. At some point, these remaining examples should be upgraded.

**Comment by tadayosi** [comment]
We can work on it along with #477.
