### ISSUE TITLE
Camel - Endpoint Properties

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-next#183]
Properties View accessed from an endpoint selection.

Screenshot to be replaced to show detail:
![endpoint-properties](https://user-images.githubusercontent.com/1634180/226611844-d5ec8e97-c544-4f19-9984-a554c1ed4bb8.png)

**Comment by tadayosi** [comment]
The Properties view does no more make sense to Camel 3+. Let's close it as `wontfix` for now.
