### ISSUE TITLE
Investigate why generate-camel-svg-index.js doesn't work with `import`

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#188]
Currently, [packages/hawtio/scripts/generate-camel-svg-index.js](https://github.com/hawtio/hawtio-next/blob/main/packages/hawtio/scripts/generate-camel-svg-index.js) doesn't work if the require parts to imports #164.
```
const fs = require('fs')
const path = require('path')
```

Let's investigate and rewrite it back to imports like this:
```
import fs from 'fs'
import path from 'path'
```

**Comment by joshiraez** [comment]
If it's not a priority I can take this out to investigate in blocked time

**Comment by joshiraez** [comment]
I'll be assigning myself in the meanwhile

**Comment by joshiraez** [comment]
I solved the issue and put some background about it in #241

**Comment by joshiraez** [comment]
I'll be closing this issue as well as it's fine like it is right now.
