### ISSUE TITLE
Camel - Attributes & Operations views

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#19]
They are mostly the same as what JMX plugin provides, but they are embedded in the Camel plugin. We need to find a way to reuse the parts of JMX plugin from a different plugin.

### Attributes

![Attributes](https://user-images.githubusercontent.com/156692/213156968-10793477-becc-4e5d-8432-6264cd770c45.png)

### Operations

![Operations](https://user-images.githubusercontent.com/156692/213157082-49bbd5c2-29ff-48bc-ad13-3f5a33af1c5a.png)

**Comment by joshiraez** [comment]
Could I work on this?

**Comment by tadayosi** [comment]
@joshiraez I think Paul is already doing it partly for Camel plugin. This task is a bit complicated to implement, since it requires to consider to what extent they should share the impl with JMX plugin. So, it should be easier for him to complete it. @phantomjinx What do you think?

**Comment by phantomjinx** [comment]
For the Camel Plugin, this is in fact complete since the Camel version of the Attributes View **is** the JMX [version](https://github.com/hawtio/hawtio-integration/blob/main/plugins/camel/ts/camelPlugin.ts#L41). Closing as #125 relates to only JMX plugin tree selections.
