### ISSUE TITLE
Add E2E tests for `yarn start` at `app` package

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#190]
Sometimes dependabot upgrades break `yarn start` (e.g. #179), but currently there are no CI workflows to catch those errors in advance. We should add some basic E2E tests that ensures `yarn start` at `app` package doesn't break.

Is React Testing Library provide sufficient for providing such E2E tests?  Or should we consider introducing an E2E framework like [Cypress](https://www.cypress.io/)?

**Comment by mmuzikar** [comment]
Done with #322
