### ISSUE TITLE
Add help tip hovers to preferences pages

### ISSUE THREAD

**Issue by joshiraez** [hawtio/hawtio-next#195]
Right now we are building the preference components without the help tip hover that Hawt.IO had. Implement them

![image](https://user-images.githubusercontent.com/17336236/227255667-6b46b145-6f14-45bd-a6b6-6822fb0ed068.png)

**Comment by joshiraez** [comment]
I'll be assigning myself for the time being but as this is a great issue for new contributors feel free to ask if you want it and I'll lend it to you

**Comment by tadayosi** [comment]
it's somewhat important. let's address it in 0.3.0

**Comment by joshiraez** [comment]
I have to fix some styling issues and it should be ready by tomorrow
