### ISSUE TITLE
Camel - Routes view

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#20]
Camel plugin should provide the view for managing Camel routes from the web console.

It should provides the following features:

- [x] Start, stop, resume, and delete Camel routes
- [x] View ~and update~ the source of the routes on the fly (Updating routes on the fly is no longer supported in Camel 3 hawtio/hawtio#2779)
- [x] https://github.com/hawtio/hawtio-next/issues/144
- [x] https://github.com/hawtio/hawtio-next/issues/145

### Routes

![Routes](https://user-images.githubusercontent.com/156692/213158904-f47dda6f-88c9-415e-be91-e63979b3a0f6.png)

### Source

![Source](https://user-images.githubusercontent.com/156692/213165492-89c27991-9fe1-4a3f-abff-84ea3861fc52.png)

### Exchanges

![Exchanges](https://user-images.githubusercontent.com/156692/213165621-b737ca54-fccb-4957-960a-8ae78260e9bc.png)

### Type converters

![Type converters](https://user-images.githubusercontent.com/156692/213165725-130974d1-5f79-40ed-9e53-9b690826b810.png)

**Comment by tadayosi** [comment]
@mmelko Can we close this?

**Comment by mmelko** [comment]
@tadayosi yes I think so. Now we have source and routes views in place.
