### ISSUE TITLE
Implement consumers for Camel preferences

### ISSUE THREAD

**Issue by joshiraez** [hawtio/hawtio-next#219]
Right now the camel preferences are stored but not used

```
export type CamelOptions = {
  isHideOptionDocumentation: boolean
  isHideDefaultOptionValues: boolean
  isHideUnusedOptionValues: boolean
  isIncludeTraceDebugStreams: boolean
  maximumTraceDebugBodyLength: number
  maximumLabelWidth: number
  isIgnoreIDForLabel: boolean
  isShowInflightCounter: boolean
  routeMetricMaximumSeconds: number
}
```

According to the help tips in the other version, I think these are pertaining to the following issues to consume them

* isHideOptionDocumentation -> #186 #185 Maybe #22 ?
* isHideDefaultOptionValues -> #185 
* isHideUnusedOptionValues -> #185 
* isIncludeTraceDebugStreams -> #23 
* maximumTraceDebugBodyLength -> #23 
* maximumLabelWidth -> #22 
* isIgnoreIDForLabel -> #22 
* isShowInflightCounter -> #22 
* routeMetricMaximumSeconds -> #185 and maybe #22

**Comment by joshiraez** [comment]
I've just assigned the issue to @mmelko  and @phantomjinx  because they are working on the related issues

**Comment by tadayosi** [comment]
@phantomjinx @mmelko Could you check the Camel views you authored and try to find places where the preferences parameters should be integrated with the logic?

**Comment by joshiraez** [comment]
I think this is safe to close. I kept looking at the pages while they were being developed and all are correctly using the consumers. I'll close this. (I kind of expected it to be closed on its own after every linked issue was closed. Sorry)
