### ISSUE TITLE
Camel/JMX - Add drag to separation between tree and content to adjust size of both 

### ISSUE THREAD

**Issue by joshiraez** [hawtio/hawtio-next#223]
![image](https://user-images.githubusercontent.com/17336236/230076134-5d7ed57b-3263-4e07-bb50-b9cacb65689b.png)

Old HawtIo had a drag to adjust the size the tree and content. It would be nice to implement it.

**Comment by tadayosi** [comment]
We already have it :thinking: 

[Screencast from 2023-04-06 15-35-28.webm](https://user-images.githubusercontent.com/156692/230291404-6289a638-82bd-4c4d-b64f-9555b0f52c99.webm)

**Comment by tadayosi** [comment]
Can we close? @joshiraez

**Comment by joshiraez** [comment]
Uh, when I opened it I didnt had it.

Let me check it out again. Sorry, I just saw this.
