### ISSUE TITLE
Camel - The order of Camel nav items seems random

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#237]
The navigation items in the Camel main content view seems random. We should maintain a consistent order of the items, starting from `Attributes` and `Operations` in order to be consistent with JMX view.

![image](https://user-images.githubusercontent.com/156692/231965539-18dc983b-20e1-440b-be33-03563592d8e9.png)

Checking the legacy Hawtio, it also has some random order in the nav, so it cannot be reused. We should define a clear and sensible order here.

For example:
- Attributes > Operations > Contexts > Routes > Endpoints > Route Diagram > Source > Exchanges > Type Converters > Chart

Any better ideas?

**Comment by tadayosi** [comment]
cc @phantomjinx @mmelko

**Comment by joshiraez** [comment]
The order of the items is defined here https://github.com/hawtio/hawtio-next/blob/4f62984aabf574adb48da89f9fa582cb695a0c5b/packages/hawtio/src/plugins/camel/CamelContent.tsx#L61 we would only to have to change the order in the list.

I think your example is fine, other than swapping the routes diagram tab so its next to routes (maybe before it)

I can do this in a second (or any of us) if we agree in the order.

**Comment by joshiraez** [comment]
I created a small PR #239  with the order you proposed tadayosi as they seem fine enough by me and it was quite quick. Feel free to reorder it if you come with a better ordering after further talk
