### ISSUE TITLE
Camel - No need for the root node `org.apache.camel` in Camel tree view

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#238]
I don't think we need this `org.apache.camel` root node in the tree view and we can start from `Camel Contexts`. It's just redundant.

![image](https://user-images.githubusercontent.com/156692/231968039-f0954348-d0ce-43a1-bfb4-770436020be3.png)

**Comment by tadayosi** [comment]
cc @phantomjinx @mmelko

**Comment by joshiraez** [comment]
As far as @phantomjinx told me, from that root context there should be some more nodes for routes and other operations that are coming from other feats. I dont know if I misunderstood that.

On top of that, the other version also has this node and Im unsure if also it could complicate the logic in the tree view as JMX also has that node and it would be akward to just directly have Camel Context directly when the other nodes have their parent folders.

**Comment by phantomjinx** [comment]
Actually, that should not be an issue. The [TreeProcessor](https://github.com/hawtio/hawtio-next/blob/main/packages/hawtio/src/plugins/camel/tree-processor.ts#L40) is responsible for resorting the JMX tree on load and sure enough the `domain` node is retained and so shown in the JMX tree.

However, the Camel tree is displayed by the [CamelTreeView](https://github.com/hawtio/hawtio-next/blob/main/packages/hawtio/src/plugins/camel/CamelTreeView.tsx) component and its display tree is already modified with respect to the possibility of being [filtered](https://github.com/hawtio/hawtio-next/blob/main/packages/hawtio/src/plugins/camel/CamelTreeView.tsx#L32). As such, adjusting that to `tree.getTree().getChildren()[0]` (obviously safety tested) should not be too difficult.

**Comment by joshiraez** [comment]
You have a point. We already are filtering the tree without any problems so there should be no problems to remove that node at all

**Comment by tadayosi** [comment]
Considering #126, we can even remove the root `Camel Contexts` node and directly start from an actual context MBean such as `SampleCamel`.

**Comment by phantomjinx** [comment]
see https://github.com/hawtio/hawtio-next/pull/301
