### ISSUE TITLE
Bug: JMX Tree on search has weird behaviour

### ISSUE THREAD

**Issue by joshiraez** [hawtio/hawtio-next#253]
JMX tree will expand all nodes on every search, even when there is no results. Trying to empty the search string will also expand all icons.

Happens in Camel tree as well

**Comment by joshiraez** [comment]
Need opinions on this @tadayosi @phantomjinx @mmelko 

Currently, search is configured to always Expand ALL the tree view on every search. I think this was done to show search hits directly on children mbeans but it becomes a bit difficult to look for what you need because with small searches like an 'A' or 'Ab' (while trying to find, I don't know, About mbean or a component AboutSearch or something like that, I dunno) you get the whole tree expanded on the get go, or something very generic. You could keep writting until you get to 'About' which narrows the search a lot but
- Depending on the number of hits, or in which mbeans the hits are, you could get a LOT of mbeans displayed. For example, if it's a parent of a lot of childs.
- When removing the search, all the mbeans are kept expanded, which is very cumbersome.
- You could say "you can press the Expand/Unexpand button" but when there is a search it is currently bugged, as the tree is not expecting it to be expanded. (In any case tthis should be really easy to fix)

![Search1](https://github.com/hawtio/hawtio-next/assets/17336236/1ec59cdb-f063-4cd9-be29-15a708ee86a2)

- The patternfly docs have this behaviour in the example, https://www.patternfly.org/v4/components/tree-view/#with-search but you can try searching with the only difference that when the search is empty, it collapses every element. But you can try searching for App and see the whole tree expanded. This is configurable anyway and also an easy fix.
- There is also a bug in Patternfly search where you can't input spaces. I think I'll fill a bug request for that one because if you want to look for 'Application 1' that's impossible.

- On the bright side, if you are looking for something in particular, is interesting as you can see the search narrowing after every input. The only problem is when you put something very generic with a lot of hits.

----------

What I was expecting when using the search was to have it only show the nodes that has hits, without modifying the rest of the tree (in case you don't want to miss an mbean you had open for example). This also has some downsides.

- The big problem is that if you don't remember exactly what are you looking for, you can't see the search results narrowing little by little.
- On the other hand, it's much less intrusive for the user. As the tree expanded state is untouched and the user can manually expand the nodes to look for the mbean they are looking for.
- No related bugs with Expand/Unexpand all (but again, really easy to fix)

![searchNoExpand](https://github.com/hawtio/hawtio-next/assets/17336236/e0a894fe-a309-4dc6-b3e1-fea1a86bc86d)

I had a PR set up with this approach but I thought it was better to comment on the issue
-----------

I feel like neither approach is not really ideal. What I would like is to just expand up until the nodes that are hits, unless those nodes were already expanded beforehand. Leave every other node untouched (so when we remove the search the tree is as it was before).

I tried looking for a way around that but the isExpanded prop is private. Although you can kiiiinda get something using the defaultExpanded prop and kiiiiinda works. I'm still working on it

Video showing this approach:

![search3](https://github.com/hawtio/hawtio-next/assets/17336236/fd2855bc-0baa-40b8-ab64-f04ff2557e2d)

Although it doesn't work as I'd like because when you remove the search everything  the search hit is still expanded. The internal TreeListViewItem doesn't refresh its internal isExpanded unless a parent node is Collapsed. There is a way around it doing two rerenders (First with CollapseAll and then with Default in the ExpandAll prop) or with events (if you click on parent nodes to collapse them, all children nodes go back to the defaultExpanded) but I feel like it's just not worth the code debt generated to do so.

Maybe is worth just leaving it as is and await for customer input. When I originally did the ticket I was just surprised that everything got expanded on a keystroke but after investigating it, I dunno. I'd like to go with the third approach but maybe it's not worth the effort.

What are your thoughts?

**Comment by tadayosi** [comment]
@joshiraez Sorry, the report is very detailed but I don't get what's the real problem with the search bar right now.

It seems to me that the search bar mostly works as expected. The only issue I can see is when I input something like `|` which should not hit any results, it still shows all the tree instead of emptying it. And once I hit the `x` sign to clear the input it then expands all the tree. Is it what you are talking about?

[Screencast from 2023-06-22 17-47-41.webm](https://github.com/hawtio/hawtio-next/assets/156692/0a9e3737-4685-4759-875c-3a6b8c33c2ab)

**Comment by joshiraez** [comment]
I'm going to close this for now as I think there are no strong arguments to change it to any of the three possible ways.

We can revisit it later after we have customer input on this.
