### ISSUE TITLE
Add test for checking html component tree has consistent ids

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#258]
For downstream E2E testing, it is important that the generated HTML components have some meaningful ids hawtio/hawtio#2826. So, ideally we should have some test that checks whether we've assigned some ids in a consistent way within hawtio-next project. I wonder if we can write such a test using React Testing Library.

**Comment by tadayosi** [comment]
cc @joshiraez

**Comment by joshiraez** [comment]
I can take care of this. Assigning myself.

I was wondering what is the behaviour we should have after #238 is added. I will do some tests for the current behaviour but what happens with the removed nodes? Should we remove the nodes directly from the tree and ignore them while in id composition? (The tests should be fairly easy still to change, just wondering)

**Comment by joshiraez** [comment]
I'm now on this and after that i'll start right away with the 0.4.0 tickets (most likely the Logs plugin)
