### ISSUE TITLE
Camel tree nodes overlay on another section when a smaller screen resolution is used

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#262]
https://github.com/hawtio/hawtio/issues/2824

When a smaller screen resolution is used, Camel tree items/nodes overlay on another UI section

![image](https://user-images.githubusercontent.com/49488040/234301055-e7ae95cd-e94e-480f-8b79-a47f13e55db8.png)

**Comment by tadayosi** [comment]
Actually, word wrapping works with the Split.js. Overlays happen when it's a long single word (no spaces in between).

What we need to do would be to shorten the words until it fits within the split frame when otherwise overlay might happen, e.g. `a-mbean-with-long-name` -> `a-mbean-with-...`

**Comment by joshiraez** [comment]
Closing this as it was merged :)
