### ISSUE TITLE
Enhancement: Show active tab when switching between Camel tree nodes  

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#267]
When switching between Camel tree nodes, the Attributes tab is shown by default but it is not indicated. 
<img width="1710" alt="Screenshot 2023-05-03 at 12 19 46" src="https://user-images.githubusercontent.com/49488040/235890687-1851da31-6adb-45b4-88c9-21f7fe6c5017.png">

When clicking on the Attributes tab on purpose (or on other tabs) it changes and starts showing an active state.
<img width="1711" alt="Screenshot 2023-05-03 at 12 19 35" src="https://user-images.githubusercontent.com/49488040/235890767-83fede0b-40b7-4c47-970b-a51d85be3247.png">

**Comment by tadayosi** [comment]
It's possible that it's caused by some misconfigration of React Router.
