### ISSUE TITLE
Enhancement: Improve scrolling when adding a new endpoint from Data

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#268]
There is inconvenient scrolling when adding a new endpoint from Data and selecting a component.

Perhaps, the UI section should be bigger and/or scrolling should be implement differently.

Check the screen recordings. 

https://user-images.githubusercontent.com/49488040/235914102-bbcbe226-ca2d-4b88-8810-309c6444458d.mov

**Comment by joshiraez** [comment]
I think the issue here lies in that the Page isFilled is not set. Let me check it out but it might be better to leave as goodfirstissue for anyone
