### ISSUE TITLE
UI - About modal

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#27]
The About modal should collect and display the right versions of components. Refer to how the legacy Hawtio substitutes the `PACKAGE_VERSION_PLACEHOLDER` string during build & publish.

- https://github.com/hawtio/hawtio-core/tree/main/src/app/about

![About](https://user-images.githubusercontent.com/156692/214836275-b8de23ef-f59c-45bb-a92f-b6e357fc1ba3.png)

**Comment by joshiraez** [comment]
I'll take this

**Comment by tadayosi** [comment]
@joshiraez I found that this task is closely related to https://github.com/hawtio/hawtio-next/issues/29 so it may require extra consideration. Mind if I take this task instead?
