### ISSUE TITLE
Bug: Button for a drop-down menu is not working in Camel Operations

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#273]
The button (3 dots) doesn't react on clicking. I assume the click on it should show a drop-down menu.

![Screenshot 2023-05-04 at 13 53 54](https://user-images.githubusercontent.com/49488040/236196644-583339ce-4e58-48a6-ad14-f8eb6023b830.png)

**Comment by tadayosi** [comment]
Issue acknowleged. Can anyone look into it? @joshiraez ?

**Comment by joshiraez** [comment]
I'll assign myself and take a look at it
