### ISSUE TITLE
JMX/Camel - Implement copy method name & Jolokia URL actions

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#278]
We still haven't implemented the following actions in the JMX Operations view:
- Copy method name
- Copy Jolokia URL

![image](https://user-images.githubusercontent.com/156692/236746228-9bf495d8-501a-4de7-b0e2-6bd6ea04fa9a.png)

Related to but not a duplicate of #273.

**Comment by tadayosi** [comment]
cc @joshiraez

**Comment by joshiraez** [comment]
I'll be picking this up after finishing the chart component

**Comment by tadayosi** [comment]
We'd like to have it in 0.3.0 so I'll take it. @joshiraez Please focus on #195 instead next, if you don't have other important tasks after Chart.

**Comment by joshiraez** [comment]
Hey Tada, I'm halfway here and I realized is for 0.3.0 and we need it for
the end of June.

Do you mind letting me finish it please?
