### ISSUE TITLE
Connect - Preferences

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#28]
Connect prefenreces is not yet fully implemented. See `// TODO` comments in `ConnectPreferences.tsx`.

What should be implemented:

- Apply the parameters to Jolokia instance
- Reset the connections settings persisted in local storage

![Connect preferences](https://user-images.githubusercontent.com/156692/214837685-660649ff-466f-4083-b021-3a782d0aa4e2.png)

**Comment by joshiraez** [comment]
I'll take this

**Comment by joshiraez** [comment]
I'm starting with this
