### ISSUE TITLE
Connect - Discovery

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#30]
Connect plugin should provide Discovery tab that allows users to discover locally running Jolokia agents automatically.

The code from hawtio-integration (v2):
- https://github.com/hawtio/hawtio-integration/blob/main/plugins/jvm/ts/discover.ts

**Comment by tadayosi** [comment]
@lhein Do we want this in 1.0.0?  Since it's turned out to be needed for integration with camel-jbang.

**Comment by lhein** [comment]
Was that part of the old HawtIO? If not we should discuss how much effort that means and also define the priority.

**Comment by tadayosi** [comment]
Yes, that was part of the Hawtio v2. It turned out camel-jbang has been relying on the tab to connect to a camel app:

![image](https://github.com/hawtio/hawtio-next/assets/156692/d5491c26-fa5b-415a-b2bc-504b4710cee1)

**Comment by lhein** [comment]
Then I would try to get it in.
