### ISSUE TITLE
JMX Operation prints "Operation succeeded" instead of false for boolean operations

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio-next#311]
If an operation is returning boolean type then only `true` returns get printed out. If the operation returns false then instead of `false`  "Operation succeeded" is printed - which isn't providing much info.
Example: 
In this example the Camel Context `isLogMask` returns `false`, but "operation succeeded" doesn't tell the user much. 
![image](https://github.com/hawtio/hawtio-next/assets/46345469/98ceb532-3c9d-4595-b126-23fd9df4c96c)

**Comment by tadayosi** [comment]
@mmuzikar Interesting bug. Thanks for your reporting.
