### ISSUE TITLE
JMX Operation input looses focus after a key is pressed

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio-next#317]
When a user want's to execute a JMX operation with a parameter it's really difficult to set the parameters as the input for the parameter loses focus after each keypress. As an example: 
![Peek 2023-06-05 10-13](https://github.com/hawtio/hawtio-next/assets/46345469/3a8ccc79-0bf3-4318-8572-395d86a9a177)

**Comment by tadayosi** [comment]
@mmuzikar Thanks for your report. Where did you try this?  I found that sometime things like this can happen only with the dev server (i.e. `yarn start`), but not with a production build. Do you think it's still reproducible with the downstream hawtio standalone project?

**Comment by mmuzikar** [comment]
It's happening when running the application in `:hawtio-tests-springboot`, no ui dev server.

**Comment by mmuzikar** [comment]
No it also happens on the examples, tested in `hawtio-example-springboot` when running with spring-boot:run
