### ISSUE TITLE
Help page issues

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio-next#327]
There are some small issues with the Help page. Such as:
- When a user navigates to the Help page, no section is enabled by default
![image](https://github.com/hawtio/hawtio-next/assets/46345469/f5ec9dbc-5be5-4bca-b1e9-e37b528c7323)
- Preferences section references an icon that doesn't get rendered
![image](https://github.com/hawtio/hawtio-next/assets/46345469/a449a442-7a00-44d6-b97e-cb11fd0f40b9)

**Comment by jsolovjo** [comment]
I believe it's related to https://github.com/hawtio/hawtio-next/issues/267
