### ISSUE TITLE
Example - Create an external plugin example

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#33]

**Comment by joshiraez** [comment]
Gathering info on plugin implementation to do this and the documentation

**Comment by joshiraez** [comment]
Leaving this in hold until the new API migration stabilizes.

**Comment by tadayosi** [comment]
Created two examples:
- https://github.com/hawtio/hawtio-sample-plugin-ts
- https://github.com/hawtio/hawtio-sample-war-plugin-ts
