### ISSUE TITLE
Wrong copyright year in About modal window

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#335]
Here is wrong copyright year in About modal window, I believe it's an easy fix.

<img width="1212" alt="Screenshot 2023-06-12 at 11 20 46" src="https://github.com/hawtio/hawtio-next/assets/49488040/fe6c2217-88a6-472f-9787-030f558fbf54">

**Comment by tadayosi** [comment]
@jsolovjo It should come from the `hawtconfig.json` the test app provides. Check the file under resources for the test app.

**Comment by jsolovjo** [comment]
> @jsolovjo It should come from the `hawtconfig.json` the test app provides. Check the file under resources for the test app.

Yes, you are right. So we can close this issue. Thank you.

**Comment by jsolovjo** [comment]
> @jsolovjo It should come from the `hawtconfig.json` the test app provides. Check the file under resources for the test app.

Yes, you are right. So we can close this issue. Thank you.
