### ISSUE TITLE
Need to check for negative numbers in input fields

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#337]
It turned out that it is possible to input negative numeric values in Preferences and moreover, it gets applied and the Hawtio crashes. Checked it with 3.x branch of hawtio standalone.

![Screenshot 2023-06-12 at 14 13 25](https://github.com/hawtio/hawtio-next/assets/49488040/ee2d027c-6e93-475f-b880-ae8ddea48e94)

It's understandable that a regular user won't type negative numeric values. However, a typo and/or mis-click may happen which will cause the Hawtio crash.

To fix it you can open a dev tools panel in a browser, open Application tab and clean Local Storage

**Comment by tadayosi** [comment]
Wow, it's a showstopper. When I tried inputting a negative value, it was so hard afterwards to recover Hawtio...
