### ISSUE TITLE
Replace confusing - and + signs in Camel Message Details with < and > arrows

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#338]
Can we replace `-` and `+` signs in Camel Message Details with `<` and `>` arrows?

Instead of this
![Screenshot 2023-06-12 at 16 42 26](https://github.com/hawtio/hawtio-next/assets/49488040/aa05b189-abab-4609-ae8e-15c9941e720c)

to have something like this 
![Screenshot 2023-06-12 at 16 43 03](https://github.com/hawtio/hawtio-next/assets/49488040/789dc1dd-aafb-481c-b8fd-88807a34d4a3)

I believe it will look nicer and more intuitively

**Comment by tadayosi** [comment]
@jsolovjo It should come from the design guidelines of PF 4. The guidelines don't seem to suggest that these can be substituted to `<` or `>`, so I wouldn't change as you suggested.
https://www.patternfly.org/v4/components/number-input/design-guidelines

**Comment by mmelko** [comment]
@tadayosi the question is if number input was used correctly in this case. I used it because it was the quickest solution. I've got the same feedback already from Riccardo, so it's possible that it will come from the UX team too. So I can look at this one.

**Comment by tadayosi** [comment]
@mmelko OK. By the way, we'll soon have a round of UX team review. Maybe should we wait for it before we work on this?

**Comment by mmelko** [comment]
I'm almost sure UX will bring this up :)
