### ISSUE TITLE
Document how to develop a Hawtio.next plugin

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#34]
Document the new plugin API defined and implemented at #32.

**Comment by joshiraez** [comment]
Checking info on plugin implementation to do this and the example

**Comment by joshiraez** [comment]
Leaving this in hold until the new API migration stabilizes.

**Comment by tadayosi** [comment]
We already have some documentation in readme of the examples, but leave it open so that we don't forget to write a full documentation some days.
https://github.com/hawtio/hawtio-sample-plugin-ts
https://github.com/hawtio/hawtio-sample-war-plugin-ts

**Comment by tadayosi** [comment]
Moved to hawtio/website/issues/50
