### ISSUE TITLE
Operation prints `Operation Succeeded!` instead of null when the value is null and attribute's type is String

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#340]
There is a basic Camel integration with `cron` route, which does not have value of Description attribute as an example, but instead it has `null` as value and attribute's type is `String`.

![Screenshot 2023-06-12 at 17 09 20](https://github.com/hawtio/hawtio-next/assets/49488040/205a319e-5705-41d7-8d5a-2f86bd637e69)

![Screenshot 2023-06-12 at 17 16 44](https://github.com/hawtio/hawtio-next/assets/49488040/546c664a-91c5-4cb6-8206-7b4ed91da3c3)

When executing, for instance, `getDescription()` operation - it prints `Operation succeeded!` and nothing else. However, the return value should be `null`

![Screenshot 2023-06-12 at 17 08 59](https://github.com/hawtio/hawtio-next/assets/49488040/cbfaad4f-43bc-46b6-b89b-bbe723ad6bca)

The output from the console:
```
{"request":{"mbean":"org.apache.camel:context=SampleCamel,type=routes,name=\"cron\"","type":"exec","operation":"getDescription()"},"value":null,"timestamp":1686583114,"status":200}
```

**Comment by jsolovjo** [comment]
Similar behaviour is when type of Attribute is `long` and value is `0`, the operations result is `Operation Succeeded!` instead of `0`

**Comment by joshiraez** [comment]
Hi juri. Which version is this? I'm just trying to produce your output but it comes correctly

`{"request":{"mbean":"org.apache.camel:context=SampleCamel,name=\"cron\",type=routes","type":"exec","operation":"getDescription()"},"value":null,"timestamp":1687185720,"status":200}`
![image](https://github.com/hawtio/hawtio-next/assets/17336236/5a4e63ac-c7d0-46a4-81ef-249f979dc31e)

`{"request":{"mbean":"org.apache.camel:context=SampleCamel,name=\"cron\",type=routes","type":"exec","operation":"getExchangesFailed()"},"value":0,"timestamp":1687185516,"status":200}`

![image](https://github.com/hawtio/hawtio-next/assets/17336236/762527b9-72fa-42e2-9ce7-ecedc29a143b)

Can you try this in latest main version?

**Comment by jsolovjo** [comment]
Hi @joshiraez ,
You are right, with recent changes now it works as expected and returns values correctly both `null` and `0`
So I think we can close the ticket
Thank you
