### ISSUE TITLE
Allow plugins to be served without hardcoding URLs

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio-next#348]
Currently user is required to specify URL for the plugin config, so the URLs are hardcoded to use one given port. This is an issue when running the app in a docker container with a mapped port. Then the assigned port can differ from the port that's specified in the app config. 
When running hawtio in a docker container with mapped ports everything works fine except for the plugins. So it should be possible to omit the URL for it to be served from the same endpoint as the hawtio app is running.

**Comment by mmuzikar** [comment]
It is possible to omit the URL currently by specifying empty string as the URL parameter - we should make sure this is documented or add a constructor without URL for the HawtioPlugin to document this: 
```java
        HawtioPlugin plugin = new HawtioPlugin(
            "",
            "samplePlugin",
            "./plugin");
```

**Comment by mmuzikar** [comment]
This is not possible to do in Quarkus, at least I haven't found any way to specify an empty value (because it is marked as mandatory). - this is causing the plugin scenarios to be disabled on quarkus E2E tests.

**Comment by tadayosi** [comment]
What if you specify like this?  Isn't it even possible?
```
quarkus.hawtio.plugin.sample-plugin.url = ""
```
