### ISSUE TITLE
Should we add sorting by name, value, attributes, etc. to tables how it was in older Hawtio?

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#352]
In new Hawtio there is only one table which has sorting feature
<img width="1710" alt="Screenshot 2023-06-15 at 11 04 26" src="https://github.com/hawtio/hawtio-next/assets/49488040/6f28992a-e156-44a9-8de5-59c6e44b3953">

Other tables like below do not have such a feature
<img width="1712" alt="Screenshot 2023-06-15 at 11 04 52" src="https://github.com/hawtio/hawtio-next/assets/49488040/1826fcbc-cf7a-4b35-a673-3c35f0333fec">

**Comment by tadayosi** [comment]
Yeah, it sounds like a good idea. Let's follow the PF 4 desing guidelines to add sorting features to tables where they are relevant.
https://www.patternfly.org/v4/components/table/design-guidelines

**Comment by mmelko** [comment]
@jsolovjo your example(attributes in particular endpoint) isn't sortable even in legacy hawtio. So far I've found these tables that are sortable in legacy and not in next:
context tabs:
- Endpoints (in/out)
- TypeConverters
Routes tab:
 - routes
 
so I'd start with these at first

**Comment by jsolovjo** [comment]
> @jsolovjo your example(attributes in particular endpoint) isn't sortable even in legacy hawtio. So far I've found these tables that are sortable in legacy and not in next: context tabs:
> 
> * Endpoints (in/out)
> * TypeConverters
>   Routes tab:
> * routes
> 
> so I'd start with these at first

@mmelko true, my bad - I provided poor example. Some tables have sorting feature and some don't have it in older Hawtio and I didn't check it properly when choosing the example, sorry
