### ISSUE TITLE
RBAC

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#36]
Hawtio.next needs to provide RBAC on UI based on the `canInvoke` info from Jolokia. Port [the feature](https://github.com/hawtio/hawtio-integration/tree/main/plugins/rbac) from hawtio-integration.

This includes the following subtasks:
- [x] #133 
- [x] #134

**Comment by phantomjinx** [comment]
Discussion kick-off for extending RBAC support to Keyclock authentication in addition to Kubernetes clusters.

Idea

- [ ] Extend RBAC `canInvoke` for the Add button in the Endpoints View (disabled if canInvoke is false)
- [ ] Implement keycloak support for authentication in a sample app tied into hawtio (embedded or standalone???)
- [ ] Add role to keycloak specifically disabling support for Add button - something like can add new stuff to app
- [ ] Tie the role to the rbac tree processor / canInvoke permissions

Further Considerations
- Legacy hawtio has [provision](https://github.com/hawtio/hawtio-integration/blob/main/plugins/jmx/ts/workspace.ts) for disablling UI elements already and we should consider porting this. However, the implementation was considered fairly ad-hoc so need to look at consistent and overarching architecture for all elements.

**Comment by tadayosi** [comment]
Extracted the discussion to a new issue. Let's discuss it further there. Here, the planned tasks are completed, so let me close it.
