### ISSUE TITLE
Camel - Endpoint view shows nothing

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#387]
When I loot at any specific endpoint in a route, it provides no info on the endpoint, like this:
![image](https://github.com/hawtio/hawtio-next/assets/156692/365eafae-7ed0-46f4-bffe-8ed6835c9908)

Is this an expected behaviour?  @phantomjinx @mmelko @joshiraez

**Comment by phantomjinx** [comment]
No its not. It looks like the Properties view has been missed. I'll get on it.

**Comment by phantomjinx** [comment]
This Properties view is not only relevent to routes and their XML components.

The view used to be obtainable for endpoints, components and data-formats. However, these 3 required the JMX operation `explainXXXJson` (where XXX is the type concerned). This operation has been removed from Camel 3 so properties views in legacy hawtio UI relating to these types are blank.

**Comment by joshiraez** [comment]
I didn't notice this and I don't think is normal either. 

@phantomjinx from what you said, there is no way then to recover that data right now with Camel 3?

**Comment by phantomjinx** [comment]
> @phantomjinx from what you said, there is no way then to recover that data right now with Camel 3?

That I have not looked into. However, this json does not appear to be readily available.

**Comment by tadayosi** [comment]
At least we seem to be able to get the schema info of each DSL step from the camel model.
https://github.com/hawtio/hawtio-next/blob/main/packages/camel-model/src/definitions-camel-model.json

If the same level of information is not available from Camel 3 as before, maybe we can be creative here and think up what we can show for the view instead. What info would be helpful to gather for each DSL step from the runtime?

**Comment by mmelko** [comment]
@phantomjinx if you are not free I implement Tada's suggestion

**Comment by phantomjinx** [comment]
See PR https://github.com/hawtio/hawtio-next/pull/392 for implementation of Properties View for routes and their xml components
