### ISSUE TITLE
Camel - Help & preferences

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#41]
#### Help

![Help](https://user-images.githubusercontent.com/156692/215407541-d64304e8-49df-4b71-8d2b-6501547a7067.png)

#### Preferences

![Preferences](https://user-images.githubusercontent.com/156692/215407663-e559c11d-cb8b-4733-adae-57fe911fd15d.png)

**Comment by joshiraez** [comment]
Can I pick this one up as future after finishing my current 2 tasks?

**Comment by tadayosi** [comment]
Thanks, you can work on this next.

**Comment by joshiraez** [comment]
For the preferences page, old version didn't have a Reset button. Do we want one for this one too? I can see that in Connect Preferences (previously Jolokla preferences) there wasn't a reset button either and we implemented it for this version

**Comment by lhein** [comment]
both PRs are merged. Can this issue be closed?

**Comment by joshiraez** [comment]
The only thing left to do is the consumers side, whose components might have not yet be implemented. Ill check tomorrow and see which open issues for the camel plugin are related to the preferences and link them

**Comment by tadayosi** [comment]
@joshiraez Can you file a new issue to track the task?  Since this one is already closed and a bit inconvenient to track todos with it.

**Comment by joshiraez** [comment]
Sure
