### ISSUE TITLE
Warning `findDOMNode is deprecated in StrictMode` when sorting columns in Camel Routes view

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#432]
Issue similar to #13. To fix it, the `removeFindDomNode` property should be provided from PF 4, but quickly searching the PF 4 React issues I couldn't find any tickets or pull reqs that fixed it. We might need to raise an issue against PF 4 React.

![image](https://github.com/hawtio/hawtio-next/assets/156692/a3249c03-eb2c-40cd-ad76-83cc38313ea1)

**Comment by tadayosi** [comment]
FYI @mmelko

**Comment by mmelko** [comment]
I'm not sure. This is similar to other pages and tables without this problem .. I think problem might be actually in the code. I will check it

**Comment by mmelko** [comment]
ok so problem is actually in the intertied Popper in the table head.  That is active when Column header is to small to display whole name such as:
<img width="126" alt="Screenshot 2023-10-04 153146" src="https://github.com/hawtio/hawtio-next/assets/6814482/b5cc53ad-8b01-48ae-adc1-d97d1ced9b5c">

  So To mitigate this  would be `<Thead noWrap={false}>` that basically prevents to get the header smaller.
