### ISSUE TITLE
Consider stopping the use of CRA

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#455]
Create React App (CRA) seems to be deprecated.
- https://github.com/facebook/create-react-app/issues/13072
- https://dev.to/ag2byte/create-react-app-is-officially-dead-h7o

It shouldn't impact our development soon, because we use it only at the last stage of building a Hawtio app and `@hawtio/react` is built with tsup. It only affects the `app` test package in this project, and downsteam it should affect the way we bundle the hawtio-next console in the hawtio standalone project, and custom plugins that are built with hawtio-next.

But let's consider switching from CRA to some other framework in the mid term. Options include:
- Eject CRA and use Webpack directly
- Migrate to other framework like Vite or Next.js

**Comment by phantomjinx** [comment]
Heavily into creating simple test apps for kubernetes on oauth in hawtio-online so can experiment with vite in them.

**Comment by phantomjinx** [comment]
Used the [oauth test app](https://github.com/hawtio/hawtio-online/blob/2.x/packages/oauth-app/webpack.config.js) in hawtio-online to protoype a pure-webpack build configuration, thus dropping craco and react-scripts.

**Comment by tadayosi** [comment]
> Used the [oauth test app](https://github.com/hawtio/hawtio-online/blob/2.x/packages/oauth-app/webpack.config.js) in hawtio-online to protoype a pure-webpack build configuration, thus dropping craco and react-scripts.

So you ejected CRA instead of trying Vite or something else?  Did you have any problem with using Vite?  Just out of curiosity.

**Comment by phantomjinx** [comment]
No. Actually, it didn't occur to me to try Vite or NextJS until I was halfway through. I'd already gone the pure-webpack route in my own project based on [kaoto-ui](https://github.com/KaotoIO/kaoto-ui/) so copied that process. I have the kubernete-api-app to convert from CRA as well so I can try that with Vite and see if its 'easier'.

**Comment by phantomjinx** [comment]
@tadayosi 
Had a first look at migrating kubernetes-api-app to vite and this was the result:
https://github.com/hawtio/hawtio-online/issues/147

Appreciate if you have more experience of `vite`, could you have a look as I have probably overlooked something or made some newbie errors.

**Comment by grgrzybek** [comment]
Maybe not related, but I found interesting discussion about module-federation impact when using shared modules: https://medium.com/@marvusm.mmi/webpack-module-federation-think-twice-before-sharing-a-dependency-18b3b0e352cb
