### ISSUE TITLE
E2E - E2E Test workflow is flaky

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#478]
For instance, this pull req required twice to pass the workflow. Some PRs require more and still fail to pass it.
https://github.com/hawtio/hawtio-next/actions/runs/5701830924

**Comment by tadayosi** [comment]
@mmuzikar Could you have a look?  Now it's very important to make the E2E stable so that we can receive and merge contributions without stopping them by the false alarms. Some checks in the E2E could be even degraded if it contributes to stabilisation of the check.

**Comment by mmuzikar** [comment]
I have it on my radar. From my observations is almost always chrome issue. I will investigate further but for PRs we could temporarily not run on chrome.

**Comment by tadayosi** [comment]
@mmuzikar Right now, flakiness of the e2e tests with chrome is unmanageable. It's stopping smooth merging of pull reqs. Let me disable the chrome tests for a while. Once you can find a resolution to make it reliable, we can restore it again.

**Comment by mmuzikar** [comment]
@tadayosi sure thing, I will continue to investigate sorry it's taking so long

**Comment by tadayosi** [comment]
CI has been stable for some time. Let's close it and we can revisit it with a new issue when we observe the flakiness again.
