### ISSUE TITLE
Chart X Axis labels are not correct

### ISSUE THREAD

**Issue by lhein** [hawtio/hawtio-next#489]
While the old HawtIO chart had a X Axis labeling of <hh:mm> to represent the current time the new chart has a label <mm:ss> which is not helpful. 

This issue is linked to #10 .

**Comment by lhein** [comment]
Old HawtIO Screenshot:
![grafik](https://github.com/hawtio/hawtio-next/assets/435853/03d0b537-e800-496e-854f-13ac36712f8c)

New HawtIO Screenshot:
![grafik](https://github.com/hawtio/hawtio-next/assets/435853/34508e66-04dc-41ec-915a-a5eaa63893d1)

**Comment by mmuzikar** [comment]
Probably a duplicate of  #437

**Comment by jsolovjo** [comment]
I agree that the current view is not in the best shape. It would be great to have the values displayed without hovering and having an Y-axis would be great as well
