### ISSUE TITLE
Camel Chart data history

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#516]
Hello,

Do you think it would be a good idea to have a Camel Chart history?

The current state is the following:

- Every time the Camel Chart is opened, it shows the only data from the time moment when the Camel Chart was opened by an user;
- If the user switches between the Camel tabs and gets back to the Camel Chart, the chart will show the only data from the time the Camel Chart was opened again and won't show you any data from the past;
- If Hawtio is running for a long time - it won't show any data from the past (e.g. routes, delta time, etc.) if the Camel Chart wasn't opened and has got accessed recently;

The propose is to have and display the Camel Chart data history and perhaps, have some preferences whether users would like to keep the history, for what time period, what kind of data, etc.

@tadayosi what do you think about it?

@lhein we could also ask Torsten about this idea whether customers/users need it and will use this feature

Thank you

cc: @mmuzikar

**Comment by tadayosi** [comment]
@jsolovjo It's an interesting idea, but it also challenges the architecture of Hawtio. Hawtio is mainly a frontend technology, so there is no backend datastore available in general. So if we'd like to store chart history somewhere, we could only use browser local storage. I'm not sure how many data we could accommodate in the local storage, and it might also hit browser performance.

Hawtio is not a general-purpose monitoring tool, rather focusing on management of applications. Chat is an easy feature to view the attribute changes quickly. If users want to view the full history of application states, they should rather use full-fledged monitoring tools such as Prometheus and Grafana.

Currently there's a problem in Chart view #489, and once it's fixed it might become a bit more useful.
