### ISSUE TITLE
Core - Home preferences

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#55]
The Home preferences is not fully implemented yet.

What should be implemented:

- Switch to show/hide the vertical navigation by default
- Reset button to clear all Hawtio settings in the local storage

![Home](https://user-images.githubusercontent.com/156692/215453851-7b4c3ca9-45b1-4036-a9dd-055a8ebe0e6f.png)

**Comment by tadayosi** [comment]
@joshiraez Could you take a look at this as well?

**Comment by joshiraez** [comment]
Yes, I'll be picking this up. Sorry for the late response

**Comment by joshiraez** [comment]
Does the behaviour of the actual preference have to be implemented in this ticket as well?

**Comment by tadayosi** [comment]
@joshiraez Yes, that's what this ticket expects to implement. The UI is already done, what's lacking is the actual behaviours.
