### ISSUE TITLE
Warning `findDOMNode is deprecated in StrictMode` when opening the extended dropdown menu from Example 3

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#570]
In the Hawtio header, the default dropdown items work just fine, but only the dropdown coming from an external plugin causes the `findDOMNode is deprecated in StrictMode` warning when opening it. It might be related to how Module Federation loads the dependency components, but not sure.

![image](https://github.com/hawtio/hawtio-next/assets/156692/dd8eb4d4-7aac-420e-91ba-9b9a76eb3265)

**Comment by tadayosi** [comment]
cc @phantomjinx

**Comment by mmelko** [comment]
Same issue as #432 . The problem is caused by tooltips. Quick fix would be just remove tooltips.

**Comment by tadayosi** [comment]
@mmelko Thanks. Do you think you can fix it quickly in the same way as the other ones?
