### ISSUE TITLE
Shared - Export DummyJolokia or modify JolokiaService to serve hawtio-online

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#573]
> I have had to copy this into hawtio-online in order to always return an implementation of jolokia, regardless of error. Can we export it, please?
>
> Of course, it might be that a review of `ManagedPod` might render this mute.
> 
> https://github.com/hawtio/hawtio-online/blob/2.x/packages/management-api/src/managed-pod.ts#L21
> https://github.com/hawtio/hawtio-online/blob/2.x/packages/management-api/src/managed-pod.ts#L110

_Originally posted by @phantomjinx in https://github.com/hawtio/hawtio-next/pull/569#discussion_r1335655528_

**Comment by tadayosi** [comment]
Here are my points:

* As we discussed, hawtio-online should rather use `jolokiaService` instead of directly depending on `jolokia.js`. This way, I don't think we need to export this `DummyJolokia` class.
* What's important to discuss here is really that currently jolokiaService is provided as a singleton service, whereas hawtio-online should expect to use multiple Jolokia instances with each distinct connection, because hawtio-online needs to switch to different Jolokia endpoints provided by pods. We'd rather need to consider how to change the `jolokiaService` so that it can serve hawtio-online as well.

**Comment by tadayosi** [comment]
@phantomjinx Btw, why do we need `DummyJolokia` here? In hawtio-online, if you cannot create a proper Jolokia instance with the pod, there's something wrong happening and you shouldn't provide a connection to it anyway. I don't see the reason for all the troubles to use `DummyJolokia` here.
https://github.com/hawtio/hawtio-online/blob/8a4a5f3d78b8b2dbd86a0d5c44268465a80d71cd/packages/management-api/src/managed-pod.ts#L110

**Comment by phantomjinx** [comment]
> @phantomjinx Btw, why do we need `DummyJolokia` here? In hawtio-online, if you cannot create a proper Jolokia instance with the pod, there's something wrong happening and you shouldn't provide a connection to it anyway. I don't see the reason for all the troubles to use `DummyJolokia` here. https://github.com/hawtio/hawtio-online/blob/8a4a5f3d78b8b2dbd86a0d5c44268465a80d71cd/packages/management-api/src/managed-pod.ts#L110

Yes. That's true. It was more to satisfy the Typescript requirements of always returning a jolokia instance of some kind rather than undefined. However, I agree it is an error so perhaps better to `throw` or something similar in that particular case.

**Comment by tadayosi** [comment]
I think we can close this issue. For enhancements to `jolokiaService` , we can discuss each in a separate issue if there need be.
