### ISSUE TITLE
Upgrade React Router to 6.x

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#62]
Automatic dependency upgrade https://github.com/hawtio/hawtio-next/pull/50 is failing because React Router v6 is not backward-compatible with v5.
https://reactrouter.com/en/main/upgrading/v5

We need to follow this guide to upgrade it to v6.

**Comment by Kirito-Excalibur** [comment]
Can you tell me where the BrowserRouter has been used? It's not located in index.ts in app folder.

**Comment by Faizan-omer** [comment]
Kindly assign this to me I'll work on this

**Comment by tadayosi** [comment]
Thank you for your interest in this project. At the moment, the project is still in its infancy and a bit too early to accept external contributions. Please keep an eye on the progress of the project!

**Comment by tadayosi** [comment]
fixed https://github.com/hawtio/hawtio-next/pull/84
