### ISSUE TITLE
Shared - `jolokiaService` should resolve or reject requests in case of ajax error

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#635]
Currently the operations provided by `jolokiaService` such as `readAttribute`, `writeAttribute`, `execute`, `search`, etc. rely on the default `ajaxError` callback in case of ajax error happening while performing Jolokia requests.

https://github.com/hawtio/hawtio-next/blob/50a83c44b5ce1b14dfa492388770a2d18f772178/packages/hawtio/src/plugins/shared/jolokia-service.ts#L293-L332

Since this callback is not aware of `resolve` or `reject` callback provided by each `Promise` that wraps a Jolokia operation, the processing of the request should hang in case of ajax error. This can happen when for some reason the remote Jolokia endpoint starts to stop serving requests, for instance due to authentication being expired or any other internal server error.

This should be actually mostly fine, because then the user would need to refresh the page or authenticate again to restore the working status anyway. So, practically we've observed no issues with it yet. However, it should be still considered well-behaved to make sure the operation terminates in such an exceptional case. That's why it's marked as **enhancement**.

**Comment by grgrzybek** [comment]
Hmm, I was thinking about it, but maybe it should be more long term goal - including Jolokia switch to Fetch API? (jolokia/jolokia#580)...

**Comment by tadayosi** [comment]
@grgrzybek If I remember it correctly, the issue was filed right after this fix:
https://github.com/hawtio/hawtio-next/commit/4963ed332cafbb55277880ff2aea5de11a0efa4c
it already fixed the issue for the list operation. What we need to do would be to apply the similar fix to the rest of Jolokia operations. So I think it can be fixed in a short term.
