### ISSUE TITLE
Camel - Tree view should be expanded by default

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#665]
Currently, the user needs to drill down themselves to routes, endpoints, components, etc. to reach some useful view. For usability, it should be expanded at least to the level of the first children of routes, endpoints, components. MBeans should be kept folded.

![image](https://github.com/hawtio/hawtio-next/assets/156692/87f8a295-29e5-49f4-8f03-391850762504)

**Comment by lhein** [comment]
hawtio online still shows JMX first.

**Comment by tadayosi** [comment]
@lhein It's a different issue. #653 is already fixed. It's just that hawtio-online doesn't yet upgrade hawtio-react to the latest.
