### ISSUE TITLE
Connect - Import connections

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#67]
`Export connections` is already available, but `Import connections` is not yet implemented.

This feature should basically just import the JSON file exported using `Export connections` and then persist the config into local storage.

![Import connections](https://user-images.githubusercontent.com/156692/215955616-bc1ec4bd-4194-4a01-b0bd-c960078fbebd.png)

**Comment by shubhamku044** [comment]
Can I work on this?

**Comment by joshiraez** [comment]
Working on this
