### ISSUE TITLE
What Camel model versions should we support?

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#693]
Right now, hawtio-react supports the following Camel LTS versions:

- 3.21.2
- 4.0.3

We'll keep this support list until GA, but after that we can expand its support to the latest version (4.2.0 now).

So the question is what Camel model versions should we support?  Is it enough to support LTS versions (3.x & 4.x) and the latest?  Should we also include non-LTS models such as 4.1.x?

@lhein @phantomjinx @mmelko @mmuzikar @jsolovjo @davsclaus I'd like to hear your thoughts.

**Comment by davsclaus** [comment]
Only support LTS and latest. And since this is a major new release you could consider starting at Camel v4 onwards.
There is the older hawtio version for Camel v3

**Comment by tadayosi** [comment]
@davsclaus Thanks. Camel v3 support is intended for Hawtio v3, which only supports Camel v3 and Quarkus/SB v2. After we release Hawtio v3 GA, we can consider dropping Camel v3 model fron hawtio-react, and Hawtio v4 can focus only on Camel v4 LTS.

**Comment by tadayosi** [comment]
This should be implemented with #800.
