### ISSUE TITLE
Support Azure AD / OpenID Connect

### ISSUE THREAD

**Issue by lhein** [hawtio/hawtio-next#702]
Support authentication using Azure AD (now Microsoft Entra ID).  See https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-id

----
**Linked issues**

* keycloak/keycloak#26651
* keycloak/keycloak#26782
* MicrosoftDocs/azure-docs#82875

**Comment by tadayosi** [comment]
We need to make it clear whether it's requested for Hawtio standalone or for Hawtio Online, as where to have the enhancement will differ based on that.

**Comment by tadayosi** [comment]
should be done
