### ISSUE TITLE
How to stop login from retrying once connection is lost

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#705]
It's good idea to provide an option at the Connect preferences that disables retrying connections on connection lost.

### Discussed in https://github.com/orgs/hawtio/discussions/3123

<div type='discussions-op-text'>

<sup>Originally posted by **ilxyz** December  7, 2023</sup>
Hello,

I noticed once a session expires and you are already logged into jolokia/remote jmx inside hawtio, a popup appears with the message "Connection lost. Retrying...", which keeps attempting login to hawtio with the jolokia/remote jmx credentials. This is generating a login error message per minute, which I am trying to stop from happening.

Is there a way to NOT have hawtio keep retrying the connection every minute and completely kill the session (in all windows)? Or a way to set a default refresh rate across the board in hawtio?</div>

----
related:
* #635
* hawtio/hawtio#3178

**Comment by grgrzybek** [comment]
With improvements from #906 I'll simply disable the toast. Failed connection will be indicated by red "disconnected" icon in the top bar.

**Comment by grgrzybek** [comment]
PR: #936
I will continue the fix for credential mismatch here: hawtio/hawtio#3178
