### ISSUE TITLE
Stop using jQuery/ajax and use Fetch API instead

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#76]
Relates #8

**Comment by phantomjinx** [comment]
Does this imply complete removal of JQuery as it is being used for parsing the XML of the camel routes? We could use something else but need to know whether to look for a replacement?

**Comment by tadayosi** [comment]
Good point. I only thought about the ajax query part of jQuery usages for the issue such as:
https://github.com/hawtio/hawtio-next/blob/main/packages/hawtio/src/plugins/connect/jolokia-service.ts#L111-L140
Yes, jQuery is also used to parse XML and it shouldn't be so easy to replace it with something else.

The motivation for this issue is to reduce as large a dependency as possible from Hawtio.next. In particular, large frameworks such as jQuery are often subject to CVEs, which means that they have to be upgraded every time. If Hawtio.next could do without jQuery, it would reduce the burden of security updates as much as possible.

This Issue has no specific milestones attached to it and does not need to be addressed now. However, it is recorded as it is something that would be beneficial to be addressed in the long term. If you have a good solution to replace something in the XML parsing part of jQuery, let's discuss it as well.

**Comment by phantomjinx** [comment]
I'm in the area of xml parsing atm so I can start to look around for an alternative and see if any do the job.

**Comment by grgrzybek** [comment]
I wasn't aware that jQuery is used for XML parsing ;)

I want to get rid of `$.ajax` call in favor of `fetch()` - Jolokia 2.1.0 already supports `fetch()` and doesn't rely on jQuery.

**Comment by phantomjinx** [comment]
> I wasn't aware that jQuery is used for XML parsing ;)
> 
> I want to get rid of `$.ajax` call in favor of `fetch()` - Jolokia 2.1.0 already supports `fetch()` and doesn't rely on jQuery.

XML parsing did use jQuery but was replaced in [this](https://github.com/hawtio/hawtio-next/commit/82b3fcf6fdfff98e54f233aa9461a960f1e8b904) commit.

**Comment by grgrzybek** [comment]
> > I wasn't aware that jQuery is used for XML parsing ;)
> > I want to get rid of `$.ajax` call in favor of `fetch()` - Jolokia 2.1.0 already supports `fetch()` and doesn't rely on jQuery.
> 
> XML parsing did use jQuery but was replaced in [this](https://github.com/hawtio/hawtio-next/commit/82b3fcf6fdfff98e54f233aa9461a960f1e8b904) commit.

cool! so I may eventually remove it entirely ;)

**Comment by phantomjinx** [comment]
Still gets used by Hawtio-Online which may or may not have an impact on this issue.

**Comment by grgrzybek** [comment]
Does hawtio-online have own dependency (in `package.json`) on JQuery? Also it should have own `import ... from 'jquery'`, right?

**Comment by phantomjinx** [comment]
> Does hawtio-online have own dependency (in `package.json`) on JQuery? Also it should have own `import ... from 'jquery'`, right?
Yes it does. It doesn't rely on hawtio-next for export of JQuery.

I mention it though since dropping it from jolokia would have implications on stuff like [this](https://github.com/hawtio/hawtio-online/blob/7832403241cf93e5e9916b2396af6b5a5d051f9c/packages/kubernetes-api/src/kubernetes-service.ts#L24)

**Comment by grgrzybek** [comment]
I'll remove `import $ from 'jquery'` from hawtio-next, but I won't remove (for now?) `jquery` from @hawtio/react's `package.json`.

**Comment by tadayosi** [comment]
Yeah, we can finally try removing jQuery from hawtio-next. I think hawtio-online can declare a dependency to jQuery itself if it still needs it after hawtio-next's removal of it.
