### ISSUE TITLE
The latest `@patternfly/react-code-editor` 5.2.0 has a breaking change that makes downstream E2E fail

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#772]
Upgrading Hawtio to `@hawtio/react` 1.0.4 (hawtio/hawtio#3227) exhibits the issue of incompatibility at `@patternfly/react-code-editor`.

Essentially, the issue is that the latest `@patternfly/react-code-editor` tries to load a script from an external CDN, which violates the CSP settings on the Hawtio standalone:

![image](https://github.com/hawtio/hawtio-next/assets/156692/4a9e2dab-acdf-4e95-a5ea-f9abc7fac595)

> index.js:86 Refused to load the script 'https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs/loader.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

This is caused by the breaking change made at `@patternfly/react-code-editor`:
* https://github.com/patternfly/patternfly-react/issues/8578

Actually, `@patternfly/react-code-editor` 5.x is for PatternFly v5, and hawtio/react is so far based on PatternFly v4 yet, so, for the time being, what we need to do is just downgrade it to 4.x. But when we upgrade PatternFly v5 #477, we'd need to fix this issue too.

**Comment by mmelko** [comment]
This was fixed by: https://github.com/hawtio/hawtio/pull/3516
