### ISSUE TITLE
Unless an url prefix is specified the connect-service throws an error when tryin to connect

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-next#793]
The [connect-service](https://github.com/hawtio/hawtio-next/blob/main/packages/hawtio/src/plugins/shared/connect-service.ts) [connect](https://github.com/hawtio/hawtio-next/blob/main/packages/hawtio/src/plugins/shared/connect-service.ts) function is responsible for loading the new window with the fresh instance of hawtio displaying the target application. It creates an URL which is passed to _window.open()_ - using _hawtio.getBasePath()_ to derive the prefix of the url, eg. for a basepath of _/online_ the url will be derived as _/online/?con=s2i-fuse711-spring-boot-2-camel-2-662k2-s2i-fuse711-spring-boot-2-camel_.

However, the url is dependent upon base path being set to a full text string. In the event that the basepath is set to `/` then the following error occurs (in development mode):

![Screenshot_20240221_195611](https://github.com/hawtio/hawtio-next/assets/1634180/4564efbb-d995-4b50-8251-3d8f6d51f8e9)

This is due to the url being derived as http://hostname//?con ....

Need to [check](https://github.com/hawtio/hawtio-next/blob/main/packages/hawtio/src/plugins/shared/connect-service.ts#L237) if the url basepath is simply a single '/' and if so do not include the second one.

**Comment by tadayosi** [comment]
@phantomjinx I think the basepath is not expected to be `/` in the current code. Can't you just set it to blank for hawtio-online?

**Comment by tadayosi** [comment]
@phantomjinx See:
https://github.com/hawtio/hawtio-next/blob/65890363187784109bbcf34f33cfceb75b1e7a12/packages/hawtio/src/core/core.ts#L120-L147

If it's just an issue in dev mode, then what about explicitly setting `basepath=/online` in dev mode as well?

**Comment by phantomjinx** [comment]
Now avoided in dev mode in hawtio-online with webpack config fixes. May need to revisit in the future if it becomes an issue for production environments.

**Comment by tadayosi** [comment]
@phantomjinx If we come up with a real scenario where it causes a problem outside of development mode, we can definitely fix the issue. Let's leave it closed until we really identify such a case.
