### ISSUE TITLE
Stop using jolokia.js and create a homebrew minimal Jolokia library

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#8]
[jolokia.js](https://github.com/hawtio/jolokia.js) depends on jQuery only for ajax communications, which is not preferrable as it will solicit a ton of vulnerabilities on jQuery to the project. We can rewrite only a subset of Jolokia functionalities that Hawtio really relies on with a lighter HTTP client library such as [axios](https://github.com/axios/axios) and switch to it.

**Comment by tadayosi** [comment]
Or maybe better to just use the built-in `fetch` API.

**Comment by joshiraez** [comment]
Can I assign myself to this? I might be able to tackle it after finishikg the JMX Chart feature

**Comment by tadayosi** [comment]
@joshiraez Don't do this now. It's a *future* task, the lowest priority. There are higher ones within 0.3 or 0.x milestones.

**Comment by tadayosi** [comment]
Let me just clear assignment to this issue for now, as we won't work on it soon.

**Comment by tadayosi** [comment]
Once the jolokia project implements this jolokia/jolokia#580 we can use it. Let's close this in favour of the Jolokia issue.
