### ISSUE TITLE
Camel - Move Start/Stop Debugging buttons to top right of the panel

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#892]
With the recent styles refactoring, the `Start/Stop Debugging` buttons are now located right under the `Debug` title in the panel. Can we move them back to the top right corner of the panel as just before?

![image](https://github.com/hawtio/hawtio-next/assets/156692/fab30935-7150-4bfd-9b4d-749c916e6d96)

**Comment by mmelko** [comment]
this was fixed by: https://github.com/hawtio/hawtio-next/pull/897
