### ISSUE TITLE
CamelPlugin: Broken Trace view

### ISSUE THREAD

**Issue by mmelko** [hawtio/hawtio-next#905]
Trace view definitely needs some care: 
<img width="1577" alt="Screenshot 2024-04-25 at 08 17 30" src="https://github.com/hawtio/hawtio-next/assets/6814482/341a25da-f374-48f0-a6d3-971d9ed419e5">

**Comment by tadayosi** [comment]
so, is it an issue after the PF style refactoring?  then, we should prioritise it if we want to merge the UI refactoring into product.

**Comment by mmelko** [comment]
No it's not. As you can see I took the picture from the product branch. I'm already working on that
