### ISSUE TITLE
Remote connection to authenticated Jolokia may cause endless redirect loop

### ISSUE THREAD

**Issue by grgrzybek** [hawtio/hawtio-next#910]
I'm still finding the exact path, but generally I was trying to connect to remote Jolokia agent with basic authentication enabled.
When connecting, I saw browser popup to enter Basic credentials for target Jolokia - when done properly, these credentials are then sent to remote Jolokia (browser adds `Authorization` header to xhr requests).

But at some point I've somehow stored bad credentials in browser's credential cache and then this `Authorization` header (with bad credentials) was added automatically not only for proxied request (to remote Jolokia), but to _main_ hawtio causing 403 and logout...

**Comment by grgrzybek** [comment]
Also I can't (yet) determine when browser popup is displayed and when Hawtio React `<ConnectLogin>` is displayed...

**Comment by grgrzybek** [comment]
Some test scenarios I found:

**Connect after clearing "HTTP authentications"**

* run `yarn start` in top level dir of hawtio-next
* start remote Jolokia application with `-javaagent:jolokia-agent-jvm-2.0.2-javaagent.jar=port=7778,protocol=http,debug=true,discoveryEnabled=true,user=grgr,password=grgr`
* import this connection:
```json
[
  {
    "name": "grgr-test-jolokia",
    "scheme": "http",
    "host": "localhost",
    "port": 7778,
    "path": "/jolokia"
  }
]
```
* CTRL-SHIFT-DEL in Firefox (or similar in Chrome) to clear _active logins_:
![image](https://github.com/hawtio/hawtio-next/assets/306565/02888c52-b306-4af8-a92c-17c7771c7a77)
* click "Connect" - new window/tab opens with URL like http://localhost:3000/hawtio/?con=name and native browser popup:
![image](https://github.com/hawtio/hawtio-next/assets/306565/e61ec091-99ef-4d79-b0e2-9842b3897f61)
* when you enter invalid credentials, these are immediately tried by the browser - you can't see it in network tab, but you can see the packet in Wireshark. Native dialog is redisplayed.
* when you click "cancel", `/hawtio/proxy/http/localhost/...` requests end with 401 and Hawtio displays React dialog to enter the credentials
   * hitting cancel closes the tab
   * hitting close (x) closes the tab
   * entering wrong credentials displays "Incorrect username or password" - 401 request is visible in Wireshark
   * entering correct credentials refreshes the page, adds `connect.salt` and `connect.credentials` to session storage and additionally browser offers to store the credentials in its own storage. only one entry in password manager is created:
![image](https://github.com/hawtio/hawtio-next/assets/306565/85537cc0-1edc-4795-8faf-1cc4cf2f33da)
   * if we then close the tab and click "Connect" again from main Hawtio and if we didn't store the credentials in browser itself, native credentials popup is displayed again
   * but I checked that after saving credentials in the browser, we still see native dialog when clicking "Connect" again...
* if you'd type valid credentials, no React dialog would be shown and Firefox would offer to store the credentials. Nothing is stored in session storage.
![image](https://github.com/hawtio/hawtio-next/assets/306565/3f0e46b7-71c7-4b79-9c4a-f34dcb5f1763)
   * if you save the credentials in browser, next time you click "Connect", no native or React dialog is shown. Two entries in password manager are stored:
![image](https://github.com/hawtio/hawtio-next/assets/306565/81d5d48c-889e-4bb2-94c3-32b65ee14a3b)

**Clearing "HTTP authentications" when connected tab is working**

(session storage should not contain encrypted credentials, so we should use the path that doesn't involve React dialog from Hawtio.)

* Connected agent's tab is opened and we can see successful `/proxy` requests
* After clearing HTTP authentications we can see native dialog during next tick for proxy request
* closing the dialog without entering credentials - page is refreshed and native dialog is displayed again
* another close - we can see React dialog
* When entering bad credentials, dialog is redisplayed
* When entering correct credentials, browser offers to save them in password manager
* I swear that once I saw full-screen login page here...

**Comment by tadayosi** [comment]
> - start remote Jolokia application with -javaagent:jolokia-agent-jvm-2.0.2-javaagent.jar=port=7778,protocol=http,debug=true,discoveryEnabled=true,user=grgr,password=grgr

We can also test it with this jbang script:
```java
///usr/bin/env jbang --javaagent=org.jolokia:jolokia-agent-jvm:2.0.2:javaagent=port=8778,protocol=http,debug=true,discoveryEnabled=true,user=grgr,password=grgr "$0" "$@" ; exit $?
//DEPS org.apache.camel:camel-bom:4.6.0@pom
//DEPS org.apache.camel:camel-core
//DEPS org.apache.camel:camel-management
//DEPS org.apache.camel:camel-main
//DEPS org.apache.camel:camel-stream
///DEPS org.slf4j:slf4j-nop:1.7.31
//DEPS org.slf4j:slf4j-simple:1.7.31

// Camel imports
import org.apache.camel.*;
import org.apache.camel.builder.*;
import org.apache.camel.main.*;
import org.apache.camel.spi.*;
import static org.apache.camel.builder.PredicateBuilder.*;

import static java.lang.System.*;

class camel_jmx {

    public static void main(String... args) throws Exception {
        out.println("Running Camel route...");

        var main = new Main();
        main.configure().addRoutesBuilder(new RouteBuilder() {
            public void configure() throws Exception {
                from("timer:hello?period=3000")
                    .setBody().constant("Hello Camel!")
                    .to("stream:out");
            }
        });
        main.run();
    }
}
```

**Comment by grgrzybek** [comment]
Closing as _can't reproduce_ and after some improvements from #832.
